/// <reference types="next" />
/// <reference types="next/image-types/global" />

/**
 * NOTE: This file is automatically generated by Next.js.
 * Do not edit this file directly.
 * See https://nextjs.org/docs/app/building-your-application/configuring/typescript
 */
